nodeLinker: node-modules

npmScopes:
  fishjam-cloud:
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN-fallback}"
    npmPublishRegistry: "https://registry.npmjs.org/"

yarnPath: .yarn/releases/yarn-4.4.1.cjs
